services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - app_net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    environment:
      REFRESH_TOKEN_NAME: ${REFRESHTOKEN_COOKIE_NAME}
      API_URL_SSR: http://backend:80
      PORT_SSR: 80
    networks:
      - app_net

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_NAME}"

      ACCESSTOKEN_SECRET: ${ACCESSTOKEN_SECRET}
      REFRESHTOKEN_SECRET: ${REFRESHTOKEN_SECRET}
      MAIL_SECRET: ${MAIL_SECRET}

      PRODUCTION: ${PRODUCTION}
      REFRESHTOKEN_COOKIE_NAME: ${REFRESHTOKEN_COOKIE_NAME}

      ACCESS_TOKEN_EXPIRES_IN_SECONDS: ${ACCESS_TOKEN_EXPIRES_IN_SECONDS}
      REFRESH_TOKEN_EXPIRES_IN_SECONDS: ${REFRESH_TOKEN_EXPIRES_IN_SECONDS}

      API_PORT: 80

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      ADMIN_USERTYPE: ${ADMIN_USERTYPE}
    volumes:
      - ./storage:/app/storage
    networks:
      - app_net

  caddy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL_TLS: ${EMAIL_TLS}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - app_net

networks:
  app_net:
    driver: bridge